local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
	Normal = { fg = "#D0CDC8", bg = "#11080D" },
	Winseparator = { link = "Normal" },
	["@boolean"] = { link = "Boolean" },
	Character = { fg = "#DA9086" },
	["@character"] = { link = "Character" },
	ColorColumn = { bg = "#572942" },
	Comment = { fg = "#534E46", italic = true },
	["@comment"] = { link = "Comment" },
	["@text.literal"] = { link = "Comment" },
	Conceal = {},
	["@conditional"] = { link = "Conditional" },
	Constant = { fg = "#5478B6" },
	Boolean = { link = "Constant" },
	Float = { link = "Constant" },
	Number = { link = "Constant" },
	["@constant"] = { link = "Constant" },
	CurSearch = { fg = "#A69582", bg = "#341828" },
	Cursor = { fg = "#11080D", bg = "#D0CDC8" },
	CursorIM = { link = "Cursor" },
	CursorColumn = { bg = "#2D281F" },
	CursorLine = { bg = "#2D281F" },
	CursorLineNr = { bg = "#2D281F" },
	["@debug"] = { link = "Debug" },
	["@define"] = { link = "Define" },
	DiagnosticError = { fg = "#EA8476" },
	DiagnosticFloatingError = { link = "DiagnosticError" },
	DiagnosticSignError = { link = "DiagnosticError" },
	DiagnosticUnderlineError = { link = "DiagnosticError" },
	DiagnosticVirtualTextError = { link = "DiagnosticError" },
	DiagnosticHint = { fg = "#8295A6" },
	DiagnosticInfo = { fg = "#8295A6" },
	DiagnosticFloatingHint = { link = "DiagnosticInfo" },
	DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
	DiagnosticSignHint = { link = "DiagnosticInfo" },
	DiagnosticSignInfo = { link = "DiagnosticInfo" },
	DiagnosticUnderlineHint = { link = "DiagnosticInfo" },
	DiagnosticUnderlineInfo = { link = "DiagnosticInfo" },
	DiagnosticVirtualTextHint = { link = "DiagnosticInfo" },
	DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
	DiagnosticOk = { fg = "#95A682" },
	DiagnosticFloatingOk = { link = "DiagnosticOk" },
	DiagnosticSignOk = { link = "DiagnosticOk" },
	DiagnosticUnderlineOk = { link = "DiagnosticOk" },
	DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
	DiagnosticWarn = { fg = "#BC956C" },
	DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
	DiagnosticSignWarn = { link = "DiagnosticWarn" },
	DiagnosticUnderlineWarn = { link = "DiagnosticWarn" },
	DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
	DiffAdd = { bg = "#566845" },
	DiffChange = { bg = "#572942" },
	DiffDelete = { bg = "#784545" },
	DiffText = { bg = "#433842" },
	Directory = { fg = "#A68295" },
	EndOfBuffer = { fg = "#524A3D" },
	Error = { fg = "#EA8476" },
	ErrorMsg = { fg = "#EA8476" },
	Exception = { fg = "#EA8476" },
	["@exception"] = { link = "Exception" },
	["@float"] = { link = "Float" },
	FloatBorder = { fg = "#A68295" },
	FloatTitle = { fg = "#EA8476" },
	FoldColumn = { fg = "#534E46" },
	CursorLineFold = { link = "FoldColumn" },
	Folded = { fg = "#D0CDC8", bg = "#341828" },
	Function = { fg = "#E2ACBB" },
	["@function"] = { link = "Function" },
	["@method"] = { link = "Function" },
	Identifier = { fg = "#D0CDC8" },
	["@field"] = { link = "Identifier" },
	["@namespace"] = { link = "Identifier" },
	["@property"] = { link = "Identifier" },
	["@text.reference"] = { link = "Identifier" },
	["@variable"] = { link = "Identifier" },
	Ignore = { fg = "#534E46" },
	IncSearch = { fg = "#11080D", bg = "#A68295" },
	WildMenu = { link = "IncSearch" },
	["@include"] = { link = "Include" },
	["@keyword"] = { link = "Keyword" },
	["@label"] = { link = "Label" },
	LineNr = { fg = "#534E46" },
	LineNrAbove = { link = "LineNr" },
	LineNrBelow = { link = "LineNr" },
	["@macro"] = { link = "Macro" },
	MatchParen = { fg = "#D0CDC8", bg = "#524A3D" },
	ModeMsg = { fg = "#B9B4AC" },
	MoreMsg = { fg = "#856397" },
	MsgArea = {},
	MsgSeparator = { fg = "#B9B4AC", bg = "#341828" },
	NonText = { fg = "#534E46" },
	Whitespace = { link = "NonText" },
	NormalFloat = { fg = "#D0CDC8" },
	NormalNC = { fg = "#D0CDC8", bg = "#11080D" },
	["@number"] = { link = "Number" },
	["@operator"] = { link = "Operator" },
	Pmenu = { fg = "#B9B4AC", bg = "#341828" },
	PmenuExtra = { link = "Pmenu" },
	PmenuKind = { link = "Pmenu" },
	PmenuSbar = { bg = "#2D281F" },
	PmenuSel = { fg = "#BC6C97", bg = "#572942" },
	PmenuExtraSel = { link = "PmenuSel" },
	PmenuKindSel = { link = "PmenuSel" },
	PmenuThumb = { bg = "#524A3D" },
	PreProc = { fg = "#856397" },
	Define = { link = "PreProc" },
	Include = { link = "PreProc" },
	Macro = { link = "PreProc" },
	PreCondit = { link = "PreProc" },
	["@preproc"] = { link = "PreProc" },
	Question = { fg = "#BC956C" },
	QuickFixLine = { fg = "#6C95BC" },
	["@repeat"] = { link = "Repeat" },
	Search = { bg = "#524A3D" },
	SignColumn = { fg = "#D0CDC8", bg = "#11080D" },
	CursorLineSign = { bg = "#2D281F" },
	Special = { fg = "#DA9086" },
	Debug = { link = "Special" },
	Delimiter = { link = "Special" },
	SpecialChar = { link = "Special" },
	SpecialComment = { link = "Special" },
	Tag = { link = "Special" },
	["@constructor"] = { link = "Special" },
	["@string.escape"] = { link = "Special" },
	["@string.special"] = { link = "Special" },
	["@character.special"] = { link = "SpecialChar" },
	SpecialKey = { fg = "#95A682" },
	SpellBad = { sp = "#DA9086", undercurl = true },
	SpellCap = { sp = "#856397", undercurl = true },
	SpellLocal = { sp = "#B9B4AC", undercurl = true },
	SpellRare = { sp = "#B9B4AC", undercurl = true },
	Statement = { fg = "#AD677C" },
	Conditional = { link = "Statement" },
	Keyword = { link = "Statement" },
	Label = { link = "Statement" },
	Operator = { link = "Statement" },
	Repeat = { link = "Statement" },
	StatusLine = { fg = "#B9B4AC", bg = "#341828" },
	StatusLineNC = { fg = "#534E46", bg = "#11080D" },
	["@storageclass"] = { link = "StorageClass" },
	String = { fg = "#F0CA93" },
	["@string"] = { link = "String" },
	["@structure"] = { link = "Structure" },
	Substitute = { bg = "#524A3D" },
	TabLine = { fg = "#B9B4AC", bg = "#341828" },
	TabLineFill = { bg = "#341828" },
	TabLineSel = { fg = "#11080D", bg = "#A68295" },
	["@tag"] = { link = "Tag" },
	TermCursor = { reverse = true },
	TermCursorNC = { reverse = true },
	Title = { fg = "#D0CDC8" },
	Todo = { fg = "#DA9086" },
	Type = { fg = "#AD677C" },
	StorageClass = { link = "Type" },
	Structure = { link = "Type" },
	Typedef = { link = "Type" },
	["@type.definition"] = { link = "Typedef" },
	Underlined = { underline = true },
	VertSplit = { fg = "#524A3D" },
	Visual = { bg = "#524A3D" },
	VisualNOS = { link = "Visual" },
	WarningMsg = { fg = "#BC956C" },
	WinBar = { fg = "#B9B4AC", bg = "#341828", bold = true },
	WinBarNC = { fg = "#B9B4AC", bg = "#341828" },
	lCursor = { fg = "#11080D", bg = "#D0CDC8" },
	netrwClassify = { fg = "#856397" },
	["@constant.builtin"] = { fg = "#8295A6" },
	["@constant.macro"] = { fg = "#8295A6" },
	["@function.builtin"] = { fg = "#7B4C67" },
	["@function.macro"] = { fg = "#7B4C67" },
	["@parameter"] = { fg = "#DA9086" },
	["@punctuation"] = { fg = "#A68295" },
	["@text.title"] = { fg = "#A68295" },
	["@text.todo"] = { fg = "#95BC6C" },
	["@text.underline"] = { underline = true },
	["@text.uri"] = { fg = "#5478B6", underline = true },
	["@type"] = { fg = "#DA9086" },
	-- PATCH_CLOSE
	-- content here will not be touched
	["markdownH1"] = { fg = "#D0CDC8", bg = "#341828", bold = true },
	["markdownH2"] = { fg = "#EA8476", bg = "#341828", bold = true },
	["markdownH3"] = { fg = "#BC6C97", bg = "#341828", bold = true },
	["markdownH4"] = { fg = "#DA9086", bg = "#341828", bold = true },
	["markdownH5"] = { fg = "#E2ACBB", bg = "#341828", bold = true },
	["markdownH6"] = { fg = "#856397", bg = "#341828", bold = true },
	["@markup.heading.1.markdown"] = { link = "markdownH1" },
	["@markup.heading.2.markdown"] = { link = "markdownH2" },
	["@markup.heading.3.markdown"] = { link = "markdownH3" },
	["@markup.heading.4.markdown"] = { link = "markdownH4" },
	["@markup.heading.5.markdown"] = { link = "markdownH5" },
	["@markup.heading.6.markdown"] = { link = "markdownH6" },
	["CmpItemAbbr"]              = { fg = "#D0CDC8" },
	["CmpItemAbbrMatch"]         = { fg = "#AD677C", bold = true },   -- 1st Match
	["CmpItemAbbrMatchFuzzy"]    = { fg = "#E2ACBB", bold = true },   -- 2nd Match
	["CmpItemMenu"]              = { fg = "#A68295", italic = true }, -- Right Text next to the item
	["CmpItemKindInterface"]     = { fg = "#DA9086", bg = "#341828" },
	["CmpItemKindColor"]         = { fg = "#E2ACBB", bg = "#341828" },
	["CmpItemKindTypeParameter"] = { fg = "#856397", bg = "#341828" },
	["CmpItemKindText"]          = { fg = "#D0CDC8", bg = "#341828" },
	["CmpItemKindEnum"]          = { fg = "#D0CDC8", bg = "#341828" },
	["CmpItemKindKeyword"]       = { fg = "#D0CDC8", bg = "#341828" },
	["CmpItemKindConstant"]      = { fg = "#EA8476", bg = "#341828" },
	["CmpItemKindConstructor"]   = { fg = "#EA8476", bg = "#341828" },
	["CmpItemKindReference"]     = { fg = "#EA8476", bg = "#341828" },
	["CmpItemKindFunction"]      = { fg = "#BC6C97", bg = "#341828" },
	["CmpItemKindStruct"]        = { fg = "#BC6C97", bg = "#341828" },
	["CmpItemKindClass"]         = { fg = "#BC6C97", bg = "#341828" },
	["CmpItemKindModule"]        = { fg = "#BC6C97", bg = "#341828" },
	["CmpItemKindOperator"]      = { fg = "#BC6C97", bg = "#341828" },
	["CmpItemKindField"]         = { fg = "#DA9086", bg = "#341828" },
	["CmpItemKindProperty"]      = { fg = "#DA9086", bg = "#341828" },
	["CmpItemKindEvent"]         = { fg = "#DA9086", bg = "#341828" },
	["CmpItemKindUnit"]          = { fg = "#E2ACBB", bg = "#341828" },
	["CmpItemKindSnippet"]       = { fg = "#E2ACBB", bg = "#341828" },
	["CmpItemKindFolder"]        = { fg = "#E2ACBB", bg = "#341828" },
	["CmpItemKindVariable"]      = { fg = "#856397", bg = "#341828" },
	["CmpItemKindFile"]          = { fg = "#856397", bg = "#341828" },
	["CmpItemKindMethod"]        = { fg = "#5478B6", bg = "#341828" },
	["CmpItemKindValue"]         = { fg = "#5478B6", bg = "#341828" },
	["CmpItemKindEnumMember"]    = { fg = "#5478B6", bg = "#341828" },
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='witchesbrew'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
